### ISSUE TITLE
todo: tiny-react follow up

### ISSUE THREAD

**Issue by hi-ogawa** [hi-ogawa/js-utils#165]
See todo list in initial PR
- https://github.com/hi-ogawa/js-utils/pull/144#issue-1918559678

---

## feat

- [ ] context https://github.com/hi-ogawa/js-utils/pull/151
- [x] ssr https://github.com/hi-ogawa/js-utils/pull/150
- [ ] memo
  - ~https://github.com/hi-ogawa/js-utils/pull/168~ it's still broken...
- [ ] compat 
  - libraries
    - react-query (context + hook?)
    - react-router (context + hook + element?)
- [ ] suspense
  - https://yew.rs/docs/concepts/suspense
  - https://github.com/yewstack/yew/blob/c5e63d8c8e52e7c221cc8df3d001b56113a1b861/packages/yew/src/dom_bundle/bsuspense.rs#L72-L73
- [ ] debug mode
  - component stack?
 
## refactor

- [x] replace `undefined` with `null` so that typescript checks missing initialization
- [x] internal `Props`, `FC` typing etc...
  - https://github.com/hi-ogawa/js-utils/pull/176
- [ ] support primitive `string | number | ...` directly as `VNode` instead of wrapping with `VText`
- [x] delay props manipulation from jsx runtime to render
  - https://github.com/hi-ogawa/js-utils/pull/172
- [ ] traverse fragment children reverse to simplify `insertBefore`
  - https://github.com/hi-ogawa/js-utils/pull/169
- [ ] fuzz children re-ordering

## perf

- [ ] "identical vnode" render optimization
  - https://github.com/hi-ogawa/js-utils/pull/163
  - https://github.com/hi-ogawa/js-utils/pull/173
- [ ] optimize children reconcilation?
  - https://github.com/yewstack/yew/blob/30e2d548ef57a4b738fb285251b986467ef7eb95/packages/yew/src/dom_bundle/blist.rs#L416
  - https://github.com/snabbdom/snabbdom/blob/420fa78abe98440d24e2c5af2f683e040409e0a6/src/init.ts#L289
  - https://github.com/WebReflection/udomdiff/blob/8923d4fac63a40c72006a46eb0af7bfb5fdef282/index.js

## chore

- [ ] define and prove "correctness" of reconcilation
- [ ] dom benchmark https://github.com/hi-ogawa/js-framework-benchmark/pull/1
